version: '3'
services:
  app:
    image: mps-app
    build: .
    tty: true
    volumes:
      - ./web:/go/src
      # - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-container
    env_file:
      - db.env
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    #   - ./initdb.d:/docker-entrypoint-initdb.d
      