version: '3'
services:
  app:
    image: mps-app
    build: .
    tty: true
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root-mps  #あとでenvファイルとかにする
      MYSQL_DATABASE: golang-mps-database